using UnityEngine;

namespace Matterless.Floorcraft
{
    /// <summary>
    /// API keys and other secrets. Kept out of source control.
    ///
    /// The asset lives at Resources/AppSecrets.asset and is generated by the editor
    /// from the project's .env file (see Docs/Secrets.md). Both files are gitignored.
    /// Never reference the asset from a scene or prefab; load it with <see cref="Load"/>.
    /// </summary>
    public class AppSecrets : ScriptableObject
    {
        public const string ResourcePath = "AppSecrets";

        [SerializeField] private string m_AukiAppKey;
        [SerializeField] private string m_AukiAppSecret;
        [SerializeField] private string m_AmplitudeApiKey;
        [SerializeField] private string m_ReownProjectId;
        [SerializeField] private string m_AlchemyApiKey;

        public string aukiAppKey => m_AukiAppKey;
        public string aukiAppSecret => m_AukiAppSecret;
        public string amplitudeApiKey => m_AmplitudeApiKey;
        public string reownProjectId => m_ReownProjectId;
        public string alchemyApiKey => m_AlchemyApiKey;

        /// <summary>
        /// Loads the generated asset. When it is missing, logs an error and returns an
        /// instance with empty values so the app still boots with the affected features disabled.
        /// </summary>
        public static AppSecrets Load()
        {
            var secrets = Resources.Load<AppSecrets>(ResourcePath);
            if (secrets != null)
            {
                return secrets;
            }

            Debug.LogError("[AppSecrets] Resources/AppSecrets.asset is missing. Copy .env.example to .env, " +
                           "fill in the keys, and let the editor regenerate it (Matterless > Secrets > Sync from .env). " +
                           "See Docs/Secrets.md. Continuing with empty secrets.");
            return CreateInstance<AppSecrets>();
        }
    }
}
